/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Certificate;
import Backend.Course;
import Backend.Student;
import Backend.StudentManagement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AliAl
 */
public class ViewEnrolledCourses extends javax.swing.JPanel {

    private Student student;
    private ArrayList<Course> courseList = new ArrayList<>();
    private DefaultTableModel tableModel;
    private StudentManagement studentManagement;

    public ViewEnrolledCourses(Student student) {
        this.student = student;
        this.studentManagement=new StudentManagement(student);
        initComponents();
        initTable();
        loadInstructorCourses();
    }
    public ViewEnrolledCourses() {
        initComponents();
        initTable();
    }
  
    /**
     * Creates new form ManageCourses
     */
    private void initTable() {
        tableModel = new DefaultTableModel(
            new String[]{"Course ID", "Title", "Description"}, 0
        );
        jTable1.setModel(tableModel);
    }

    private void loadInstructorCourses() {
        courseList = studentManagement.enrolledCourses();
            if (courseList == null) {
        courseList = new ArrayList<>();
    }
        tableModel.setRowCount(0);
        for (Course c : courseList) {
            tableModel.addRow(new Object[]{
                c.getCourseId(), c.getTitle(), c.getDescription()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("return");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setText("View Certificate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(97, 97, 97))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a course first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Course selectedCourse = courseList.get(selectedRow);

        JFrame frame = (JFrame) this.getTopLevelAncestor();
        frame.getContentPane().removeAll();
        frame.setContentPane(new ViewLessons(selectedCourse,this.student));
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFrame frame = (JFrame) this.getTopLevelAncestor();
        frame.getContentPane().removeAll();
        frame.setContentPane(new StudentDashBoard(this.student));
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a course first!");
    return;
    }

    String selectedCourseId = (String) jTable1.getValueAt(selectedRow, 0);


    Certificate cert = null;
    for (Certificate c : student.getCertificates()) { 
    if (c.getCourseId().equals(selectedCourseId)) {
        cert = c;
        break;
    }
        }

    if (cert != null) {
        JFrame mainContainer = (JFrame) this.getTopLevelAncestor();
        mainContainer.getContentPane().removeAll();
        mainContainer.setContentPane(new Certification(student,cert));
        mainContainer.revalidate();
        mainContainer.repaint();
    } else {
    JOptionPane.showMessageDialog(this, "Certificate not available. Complete the course first.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

public void refreshTable() {
    tableModel.setRowCount(0);
    for (Course c : courseList) {
        tableModel.addRow(new Object[]{c.getCourseId(), c.getTitle(), c.getDescription()});
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
